language: java
jdk: oraclejdk8
addons:
  sonarqube:
    organization: "almiselus-github"
    
stage: test
script: ignore

jobs:
  include:
    - stage: Build project
      script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: Generate tests reports
      script:
        - mvn package -Pci -B
    - stage: Run Sonar Deploy
      script: sonar-scanner
#    - stage: Deploy Master to Heroku
#      script: