language: java
jdk: oraclejdk8
addons:
  sonarqube:
    organization: almiselus-github
deploy:
  provider: heroku
  app: awesomeproject
  api_key:
    secure: ehwpe5GoGYeqydPA7Vqw+Oq7X3EAyj1lV4IaPCEGJN4HWMfnMT3F+fDoS/2KCov33il8ux3SlYsTAczDtaJN5fwSCvGCni94GBlPEdeNhV2pPJdTpgDTLvXtGqJNwCc9gv/qi/XHomAkA21znZM58m2U7uSnjk1DhQODdoHJGUUqoTBaSMOhRJ8Wo1yMZwPXLqJYiheH5unkfp6fHtbQOYmbXY//Hqh+JSCll1fGwXfclNJrEN45AsVa22GdT/NX/F6EuUDn37msms2ysFZmRcfxGMDHw9pSDpo00l1FU9sd9o1j15s6n0oTFjWF7+KDpCNUrcgxAmnN9gRUVCH0rWQHyeK6/yCj/j3bLQuVZTrGwAMLtJQg6inU/FLe88p3CUXtUxtlfwx9vkYNoAgpw7HqiGayKswZAO+yAlShpuA04sWmspOlci9lLwU7pGFDjVqi84wfo3vRz6ok6UbNySlkQueEAdzTRv8VeEGYFg3udxltAkw28d3HttuIhYPGs9yR0dujpLJvugXR/pYc9wrDxonryE1C+tb7kVdCc+i5o6eemveAARWdCZBZS1EHx+di1CiX/Sh3pwXaG6vu7LtiaclS4vV4QVGysEvEjSVliGPCUpaHyHkfAatCjSH3jzkvOm53o0ub3u4GzjMv0WKaaN9vKahZ/YvlgWm2yA8=
