language: java
jdk: oraclejdk8
addons:
  sonarqube:
    organization: "almiselus-github"
#script:
#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#  - mvn package -Pci -B
#  - sonar-scanner

stage: test
script: skip

jobs:
  include:
    - stage: test
      script: skip
    - stage: Download Development Branch
      script: git fetch && git checkout development
    - stage: Build on Development Branch
      script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: Commit To Test Branch
      script: ./deploy.sh test
    - stage: Test and report with SonarQube on Test Branch
      script:
        - git fetch && git checkout test
        - mvn package -Pci -B
    - stage: Run Sonar Deploy
      script: sonar-scanner
    - stage: Commit To Master Branch
      script: ./deploy.sh master
#    - stage: Deploy Master to Heroku
#      script: