language: java
jdk: oraclejdk8
addons:
  sonarqube:
    organization: "almiselus-github"

stage: test
script: ignore
install: ignore

jobs:
  include:
    - stage: Build project
      script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: Generate tests reports
      script:
        - mvn package -Pci -B
    - stage: Run Sonar Deploy
      script: sonar-scanner
    - stage: Push to master
      script:
        - chmod 777 merge.sh
        - ./merge.sh $GIT_USER $GIT_PASS development master
#    - stage: Deploy Master to Heroku
#      script: