language: java
jdk:
  - oraclejdk8
addons:
  sonarqube:
    organization: "almiselus-github"
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn package -Pcoverage-per-test -B
  - sonar-scanner