language: java
jdk: oraclejdk8
addons:
  sonarqube:
    organization: "almiselus-github"
    
stage: test
script: ignore

jobs:
  include:
    - stage: echo
      script: echo "TEST"
#    - stage: Deploy Master to Heroku
#      script: