language: java
jdk:
  - oraclejdk8
addons:
  sonarqube:
    organization: "almiselus-github"
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn package -Pci -B
  - sonar-scanner
  
deploy:
    provider: heroku
    api_key:
    api: awesomeproject
    